### PR TITLE
Add scroll to verse prop and on verse click callback 

### PR DESCRIPTION
**Pull request by superdav42**
This is ready to review

Check it out in the Editor component on styleguidest.
Click a verse will log the reference to the console. 

Used by https://github.com/unfoldingWord/gateway-translate/pull/131

Work needed to detect verse when the marker is in a different paragraph and other unusual cases. 

I wanted to use smooth scrolling in scrollintoview() but it did not work with multiple panes simultaneously. More research required.

UST which uses verse rancher markers are not supported. Shouldn't be too hard to add it later.

### CODE REVIEW

**Comment by birchamp** [comment]
@superdav42 can you connect this to an issue?

**Comment by superdav42** [comment]
> @superdav42 can you connect this to an issue?

It's for #65

**Comment by mandolyte** [comment]
[Screen recording 2023-01-18 7.46.21 AM.webm](https://user-images.githubusercontent.com/1289437/213175350-11dd8df2-7cff-4741-8637-3b99176adfc0.webm)
@superdav42 the chapters are off by one. See recording attached.

**Comment by superdav42** [comment]
> [Screen recording 2023-01-18 7.46.21 AM.webm](https://user-images.githubusercontent.com/1289437/213175350-11dd8df2-7cff-4741-8637-3b99176adfc0.webm) @superdav42 the chapters are off by one. See recording attached.

The intro is throwing it off. I'll need to add a check if there's an intro and adjust accordingly.

**Review by mandolyte — APPROVED** [review]
Tested in gT and works.

**Pull request merged**
